# Generated by Django 5.1.4 on 2024-12-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estoque',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='admin', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='admin', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default='admin', max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='admin', max_length=100, verbose_name='Nome'),
        ),
    ]
